[phases.setup]
nixPkgs = ['nodejs', 'nginx']

[phases.install]
cmds = ['rm -rf node_modules package-lock.json', 'npm install --force']

[phases.build]
cmds = ['npm run build']

[start]
cmd = 'npx serve -s dist -l 3000'
