// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import { getCSRFHeaders } from '@/lib/csrf-protection';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY;

if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  throw new Error('Missing Supabase environment variables. Please check your .env file.');
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    // CSRF Protection: Use SameSite cookies
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
    flowType: 'pkce', // Use PKCE flow for enhanced security
  },
  global: {
    headers: {
      // Add custom headers for CSRF protection
      ...getCSRFHeaders(),
    },
  },
  db: {
    schema: 'public',
  },
});